OR:
COND1   COND2   RES
TRUE    FALSE   TRUE
FALSE   TRUE    TRUE
TRUE    TRUE    TRUE
FALSE   FASLE   FALSE


SELECT * FROM buisket;
DESC buisket;

SELECT * FROM buisket WHERE id=10 or id=20 or price=23455;

SELECT * FROM buisket WHERE id=100 OR flavor="black" OR price=689;

SELECT * FROM buisket WHERE id=80 or flavor="black" or price=10000;

IN:

SELECT * FROM equipments where id IN(5,13,20,2);
NOT IN:
SELECT id,liquid_no FROM equipments where id NOT IN(5,13,20,2);

-- IN
SELECT * FROM buisket;

SELECT * FROM buisket where id IN(10,20,60,50);

SELECT * FROM buisket WHERE flavor IN("SALT",'MILK',"PINEAPPLE");-- //IT RETURN COMPLETE ROW

SELECT * FROM buisket WHERE id NOT IN(10,20,30,40,50,60,70);-- //it exculde and return remaining row

SELECT * FROM buisket WHERE  QUANTITY NOT IN("20 GRAMS","40 GRAMS",'50','','',);

SELECT * FROM buisket WHERE quantity NOT IN ("20grams","40grams",'60grams','70 grams','30 grams');-- //it exculde and return remaining row

-- DISPLAY Perticular column; AND NOT CASE SENSITIVE

SELECT  ID FROM buisket;
SELECT FLAVOR FROM buisket;
SELECT QUANTITY FROM BUISKET;
SELECT PRICE FROM BUISKET;
SELECT BUISKET_NAME  FROM  BUISKET;

SELECT ID,FLAVOR,BUISKET_NAME,PRICE,QUANTITY FROM BUISKET;//-- IT RETUTRNS ALL COULUM

between:

-- SELECT * FROM equipments where name between 'S' and 'W';

SELECT * FROM buisket where id between 10 and 100;

SELECT * FROM buisket WHERE flavor between "W" AND "D";-- //this case not use

SELECT * FROM buisket WHERE PRICE BETWEEN 20 AND 60;

SELECT * FROM BUISKET WHERE PRICE BETWEEN 5 AND 10;//-- THIS DATA IS NOT THEIR

SELECT * FROM buisket WHERE price between 10 and 40;

SELECT * FROM  buisket WHERE PRICE BETWEEN 10 AND 20;

-- not between:

SELECT * FROM  buisket WHERE id NOT BETWEEN 10 AND 20;-- //IT EXCULDE AND PRINT

SELECT * FROM buisket WHERE PRICE NOT BETWEEN 20 AND 40;

-- //IT WILL PRINT PERTICULAR COLUMN
SELECT PRICE FROM BUISKET;

SELECT ID FROM BUISKET;
SELECT FLAVOR,BUISKET_NAME FROM buisket;

ORDER BY:

SELECT DISTINCT FROM WHERE GROUP BY HAVING ORDER BY;
SELECT * FROM buisket;

SELECT * FROM BUISKET order by id;-- //BY DEFAULT ASCENDING
SELECT * FROM buisket order by id desc;
SELECT * FROM BUISKET ORDER BY QUANTITY;
SELECT * FROM buisket ORDER BY FLAVOR ;
SELECT * FROM buisket ORDER BY BUISKET_NAME;

DISTINCT:

SELECT DISTINCT(name) from equipments;-- //IT WILL REMOVE DUPLICATE VALUES LIKE NAME,PRICE ETC AND PRINT PERTICULAR COLUMN

SELECT DISTINCT (PRICE) FROM BUISKET;
SELECT DISTINCT (ID) FROM BUISKET;

CREATE TABLE hospital_dup as select * from hospital;-- //IT WILL CHANGE TABLE NAME

CREATE TABLE FRUIT_JUICE AS SELECT * FROM JUICE;

SELECT * FROM fruit_juice;

-- //TO CHANGE THE TABLE NAME
CREATE TABLE COLD_JUICE AS SELECT * FROM FRUIT_JUICE;
SELECT * FROM JUICE;
SELECT * FROM COLD_JUICE;
